---
name: Test using Pytest in Docker


on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master


jobs:
  test-docker:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Use GitHub's Docker registry to cache intermediate layers
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com
          -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache
          || true

      - name: Build the Docker image
        run: |
          git fetch --prune --unshallow --tags
          docker build . -t aleph-client:${GITHUB_REF##*/} -f docker/Dockerfile --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache

      - name: Push the image on GitHub's repository
        run: docker tag aleph-client:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client:${GITHUB_REF##*/}
          && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client:${GITHUB_REF##*/}
          || true

      - name: Cache the image on GitHub's repository
        run: docker tag aleph-client:${GITHUB_REF##*/} docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache
          && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/aleph-client-build-cache
          || true

      - name: Pytest in the Docker image
        run: |
          docker run -w /opt/aleph-client --entrypoint /opt/venv/bin/hatch aleph-client:${GITHUB_REF##*/} run testing:test

      - name: MyPy in the Docker image
        run: |-
          docker run -w /opt/aleph-client --entrypoint /opt/venv/bin/hatch aleph-client:${GITHUB_REF##*/} run linting:all
